### ISSUE TITLE
Plugin does not accept uints for publishing

### ISSUE THREAD

**Issue by IRCody** [intelsdi-x/snap-plugin-publisher-postgresql#15] opened 2016-05-02 17:49 UTC
Because of the implementation of [interfaceToString()](https://github.com/intelsdi-x/snap-plugin-publisher-postgresql/blob/master/postgresql/postgresql.go#L213) uints passed in as Data will result in an unsupported type error. 

Some of the procfs plugins use uints for there data. See: [meminfo](https://github.com/intelsdi-x/snap-plugin-collector-meminfo), [processes](https://github.com/intelsdi-x/snap-plugin-collector-processes).

Also see: [snap-issue-#894](https://github.com/intelsdi-x/snap/issues/894)

**Comment by IzabellaRaulin** [comment] 2016-07-04 13:46
@IRCody, I made pull request https://github.com/intelsdi-x/snap-plugin-publisher-postgresql/pull/18 which fixes that. 

I am confused why in this [interfaceToString()](https://github.com/intelsdi-x/snap-plugin-publisher-postgresql/blob/master/postgresql/postgresql.go#L213) somethink like `fmt.Sprint("%v", val)` was not used (what will simplify this "switch"), but I adjusted my changes to this existing code. But, if you also agree with that, I will gladly apply it.

What is more, maybe it's worth to take into account publishing data not as a string, but as a float (as default), but also make it configurable in task manifest - so user can decide about format of stored data. For example, the format of published data can be changed to `int`. In situation when an incoming data is float, some warning about losing data will occur. An error will be returned if there is no way to parse the incoming data to expected format. What do You think about it?

**Comment by IRCody** [comment] 2016-07-13 17:39
I agree if we are going to be publishing strings using `Sprintf` makes sense.

As far as publishing it as float by default, I'm not sure I have enough context to give an informed response. I do think the idea of having a default data type, with possible conversions to others being possible in task manifest might potentially be useful. Whether that default should be float, string, or some other type I'm not sure about. My first instinct would be to default to string since that would maintain current behavior.

**Comment by Lactem** [comment] 2016-07-14 20:30
@IzabellaRaulin I made interfaceToString() when I didn't have much experience with Go. There's no reason you have to adjust your changes to it. Feel free to use your desired `Sprintf` method!

What would be the advantage of publishing as a float rather than a string? String makes the most sense to me because all data types can be converted to a string and back (correct me if I'm wrong on that), and it's also more user-friendly for the SQL admin when he/she is looking through the database. If, for example, you want to find the value "red" in your database, it's much easier to have a simple clause like `WHERE value="red"` than to find the float equivalent of "red" and put that in the where clause instead.

**Comment by IzabellaRaulin** [comment] 2016-07-15 09:24
Thanks @Lactem for your answer. I suppose that `fmt.Sprintf()` will resolve all the issue related with type conversion, what @IRCody also confirmed that there is no more need to maintain the type switches. I am going to open the next issue to do that simplification. 

This [issue](https://github.com/intelsdi-x/snap-plugin-publisher-postgresql/issues/15) can be closed by fix https://github.com/intelsdi-x/snap-plugin-publisher-postgresql/pull/18 which is ready to be merged.


@Lactem, I've just though about support of publishing data also in different type (e.g. float, int, uint) because of processing this data after they are stored in postrgresql db (or even display them as a graph), but I agree with @IRCody that publishing to string should be a default for two reasons: a) works for all incoming data types, b) maintains current behavior. 

The discussion about support publishing to float, int, uint as well as to string can be moved to an issue which is about it.

**Closed** 2016-07-15 09:54 UTC
Labels: bug, tracked
